import type {Metadata} from 'next';
import fs from 'node:fs/promises';
import path from 'node:path';

type Assets={wordmark:string;mark:string;avatar:string;icon:string;favicon:string;og:string;facebook:string;linkedin:string;youtube:string;newsletter:string};
type Concept={id:string;name:string;description:string;assets:Assets};
type Manifest={brand:{name:string;tagline:string;domain:string;colors:Record<string,string>;activeConcept:string|null};concepts:Concept[]};
export const metadata:Metadata={title:'Brand Review',robots:{index:false,follow:false}};
export default async function BrandReview(){const manifest:Manifest=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/brand-review-assets/manifest.json'),'utf8'));return <main className="brand-review"><header className="brand-review__hero"><div><p className="brand-review__eyebrow">BUSINESS FUTURE TODAY · BRAND SYSTEM</p><h1>Brand Review</h1><p>{manifest.brand.tagline}</p></div><div className="brand-review__status"><span>ACTIVE CONCEPT</span><strong>{manifest.brand.activeConcept??'Not selected'}</strong><small>Review first. Production brand remains unchanged.</small></div></header><section className="brand-review__tokens"><div><span>Ink</span><i style={{background:manifest.brand.colors.ink}}/><code>{manifest.brand.colors.ink}</code></div><div><span>Paper</span><i style={{background:manifest.brand.colors.paper}}/><code>{manifest.brand.colors.paper}</code></div><div><span>Accent</span><i style={{background:manifest.brand.colors.accent}}/><code>{manifest.brand.colors.accent}</code></div><div><span>Muted</span><i style={{background:manifest.brand.colors.muted}}/><code>{manifest.brand.colors.muted}</code></div></section>{manifest.concepts.map((concept,index)=><ConceptSection key={concept.id} concept={concept} index={index+1}/>) }<section className="brand-review__matrix"><div><p className="brand-review__eyebrow">ASSET MATRIX</p><h2>One choice, all surfaces.</h2></div><div className="brand-review__matrixgrid"><Cell a="Master" b="Wordmark SVG · Mark SVG"/><Cell a="Web" b="Header · Footer · favicon · app icon"/><Cell a="Instagram" b="Avatar · posts · carousel · story masthead"/><Cell a="Facebook" b="Avatar · 1640×624 cover"/><Cell a="LinkedIn" b="Avatar · 1128×191 company cover"/><Cell a="YouTube" b="Avatar · 2560×1440 channel banner"/><Cell a="Editorial" b="1200×630 OG · article/social templates"/><Cell a="Email" b="1200×400 newsletter header"/></div></section></main>}
function ConceptSection({concept,index}:{concept:Concept;index:number}){const a=concept.assets;return <section className="brand-concept"><header className="brand-concept__head"><div><span>{String(index).padStart(2,'0')}</span><div><h2>{concept.name}</h2><p>{concept.description}</p></div></div><code>{concept.id}</code></header><div className="brand-concept__logos"><Asset title="Horizontal wordmark" meta="SVG · master" src={a.wordmark}/><Asset title="Standalone mark" meta="SVG · master" src={a.mark} square/></div><div className="brand-concept__small"><Asset title="Instagram / social avatar" meta="1080×1080" src={a.avatar} square/><Asset title="App icon" meta="512×512" src={a.icon} square/><Asset title="Favicon" meta="64×64" src={a.favicon} square tiny/><Asset title="Default OG" meta="1200×630" src={a.og}/></div><div className="brand-concept__banners"><Asset title="Facebook cover" meta="1640×624" src={a.facebook}/><Asset title="LinkedIn company cover" meta="1128×191" src={a.linkedin}/><Asset title="YouTube channel banner" meta="2560×1440 · safe area marked" src={a.youtube}/><Asset title="Newsletter header" meta="1200×400" src={a.newsletter}/></div></section>}
function Asset({title,meta,src,square=false,tiny=false}:{title:string;meta:string;src:string;square?:boolean;tiny?:boolean}){return <article className={`brand-asset${square?' brand-asset--square':''}${tiny?' brand-asset--tiny':''}`}><div className="brand-asset__label"><strong>{title}</strong><span>{meta}</span></div><a href={src} target="_blank" rel="noreferrer"><img src={src} alt={`${title} preview`}/></a><a href={src} target="_blank" rel="noreferrer" className="brand-asset__open">Open asset ↗</a></article>}
function Cell({a,b}:{a:string;b:string}){return <div><strong>{a}</strong><span>{b}</span></div>}
