import Link from "next/link";
import { AdSlot } from "@/components/ad-slot";
import { SubscribeForm } from "@/components/subscribe-form";
import { PublicationFooter, PublicationHeader, StoryLink } from "@/components/publication/chrome";
import type { Story } from "@/lib/content";
import { publicationBrand, type PublicationTemplate } from "@/lib/publication";
import {orderedStories,publicationSections,sectionForStory,sectionHref} from "@/lib/sections";

function StoryImage({ story, className = "" }: { story: Story; className?: string }) {
  if (!story.cardImage && !story.heroImage) return <div className={`pub-image pub-image--fallback ${className}`} aria-hidden="true"><span>BFT</span></div>;
  return <img className={`pub-image ${className}`} src={story.cardImage || story.heroImage || ""} alt={story.imageAlt || story.title} />;
}
function Meta({ story }: { story: Story }) {return <div className="pub-meta"><span>{story.author?`${story.author.name} · ${story.author.desk}`:story.category}</span><span>{story.readTime}</span></div>}

function Lead({stories,template}:{stories:Story[];template:PublicationTemplate}){const [lead,...secondary]=stories.slice(0,5);if(!lead)return null;return <section className="pub-lead pub-shell"><article className="pub-lead__primary"><StoryLink slug={lead.slug} template={template} className="pub-lead__media"><StoryImage story={lead}/></StoryLink><div className="pub-lead__copy"><p className="pub-kicker">{lead.kicker}</p><h1><StoryLink slug={lead.slug} template={template}>{lead.title}</StoryLink></h1><p className="pub-dek">{lead.dek}</p><Meta story={lead}/></div></article><div className="pub-lead__secondary">{secondary.map(story=><article className="pub-secondary" key={story.slug}><StoryLink slug={story.slug} template={template} className="pub-secondary__media"><StoryImage story={story}/></StoryLink><div><p className="pub-kicker">{story.category}</p><h2><StoryLink slug={story.slug} template={template}>{story.title}</StoryLink></h2><Meta story={story}/></div></article>)}</div></section>}

function Latest({stories,template}:{stories:Story[];template:PublicationTemplate}){return <section className="pub-section pub-shell"><div className="pub-section__head"><h2>Latest</h2><span>What just changed</span></div><div className="pub-latest">{stories.slice(0,6).map((story,index)=><article className="pub-latest__item" key={story.slug}><span className="pub-latest__number">{String(index+1).padStart(2,"0")}</span><div><p className="pub-kicker">{story.category}</p><h3><StoryLink slug={story.slug} template={template}>{story.title}</StoryLink></h3><Meta story={story}/></div>{story.cardImage?<StoryLink slug={story.slug} template={template} className="pub-latest__media"><StoryImage story={story}/></StoryLink>:null}</article>)}</div></section>}

function SectionDirectory({stories,template}:{stories:Story[];template:PublicationTemplate}){return <section className="pub-section pub-shell pub-section-directory"><div className="pub-section__head"><h2>Browse by section</h2><span>Choose your lane</span></div><div className="pub-section-directory__grid">{publicationSections.map(section=>{const items=stories.filter(story=>sectionForStory(story)===section.name);const lead=items[0];return <article key={section.id} className="pub-section-card"><div className="pub-section-card__head"><div><p className="pub-kicker">SECTION</p><h3><Link href={sectionHref(section)}>{section.name}</Link></h3></div><span>{items.length} stories</span></div>{lead?<><StoryLink slug={lead.slug} template={template} className="pub-section-card__media"><StoryImage story={lead}/></StoryLink><h4><StoryLink slug={lead.slug} template={template}>{lead.title}</StoryLink></h4><div className="pub-section-card__list">{items.slice(1,3).map(story=><StoryLink key={story.slug} slug={story.slug} template={template}>{story.title}</StoryLink>)}</div></>:null}<Link href={sectionHref(section)} className="pub-text-link">View all {section.name} →</Link></article>})}</div></section>}

function MoreStories({stories,template}:{stories:Story[];template:PublicationTemplate}){if(!stories.length)return null;return <section className="pub-section pub-shell"><div className="pub-section__head"><h2>More stories</h2><span>Keep exploring</span></div><div className="pub-home-more">{stories.slice(0,6).map(story=><article key={story.slug}><StoryLink slug={story.slug} template={template} className="pub-home-more__media"><StoryImage story={story}/></StoryLink><p className="pub-kicker">{story.category}</p><h3><StoryLink slug={story.slug} template={template}>{story.title}</StoryLink></h3><Meta story={story}/></article>)}</div></section>}

function Newsletter(){return <section id="briefing" className="pub-newsletter"><div className="pub-shell pub-newsletter__inner"><div><p className="pub-kicker">THE DAILY BRIEFING</p><h2>Know what matters before the day gets noisy.</h2></div><div><p>{publicationBrand.description} One useful briefing, built from the same publication engine.</p><SubscribeForm/><small>Unsubscribe any time. Privacy choices stay yours.</small></div></div></section>}

export function PublicationHome({ stories, template }: { stories: Story[]; template: PublicationTemplate }) {const ordered=orderedStories(stories);return <main className="publication publication--newsroom" data-template="edition"><PublicationHeader template={template}/><div className="pub-ad-band pub-shell"><AdSlot slotKey="site_top_billboard"/></div><Lead stories={ordered.slice(0,5)} template={template}/><Latest stories={ordered.slice(5,11)} template={template}/><SectionDirectory stories={ordered} template={template}/><div className="pub-ad-band pub-shell"><AdSlot slotKey="home_midfeed"/></div><MoreStories stories={ordered.slice(11,17)} template={template}/><Newsletter/><PublicationFooter template={template}/></main>}
