import{readdir,readFile}from"node:fs/promises";import path from"node:path";
const A=process.env.CLOUDFLARE_ACCOUNT_ID||"726e58dee7f6dbc6504a4c160cc21f6f",S=process.env.BFT_SOURCE_BUCKET||"businessfuture-source",P=process.env.BFT_PUBLIC_BUCKET||"businessfuture-public",T=process.env.CLOUDFLARE_API_TOKEN||"",B="refactor/businessfuture-independent-content";
if(!process.argv.includes("--force")&&(process.env.VERCEL_GIT_COMMIT_REF||"")!==B){console.log("R2 bootstrap skipped");process.exit(0)}if(!T){console.log("R2 bootstrap skipped: token missing");process.exit(0)}
const u=(b,k)=>`https://api.cloudflare.com/client/v4/accounts/${A}/r2/buckets/${b}/objects/${k.split("/").map(encodeURIComponent).join("/")}`;
async function put(b,k,x,t){let r=await fetch(u(b,k),{method:"PUT",headers:{authorization:`Bearer ${T}`,"content-type":t},body:x,signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error(`PUT ${r.status} ${b}/${k}`)}
async function walk(d,p=""){let o=[];for(const e of await readdir(d,{withFileTypes:true})){let q=p?`${p}/${e.name}`:e.name,f=path.join(d,e.name);e.isDirectory()?o.push(...await walk(f,q)):e.isFile()&&o.push({q,f})}return o}
async function map(items,n,fn){let i=0,out=[];await Promise.all(Array.from({length:Math.min(n,items.length||1)},async()=>{for(;;){let j=i++;if(j>=items.length)return;try{out[j]=await fn(items[j])}catch(e){out[j]={ok:false,error:String(e)}}}}));return out}
const root=path.join(process.cwd(),"public","media"),files=(await walk(root)).filter(x=>/\.(webp|png|jpe?g|avif|gif)$/i.test(x.q));
const pub=await map(files,8,async x=>{let b=await readFile(x.f),e=path.extname(x.q).toLowerCase(),t=e==".webp"?"image/webp":e==".png"?"image/png":e==".avif"?"image/avif":e==".gif"?"image/gif":"image/jpeg";await put(P,`media/${x.q}`,b,t);return{ok:true,key:`media/${x.q}`}});
let jobs=[],ar=path.join(process.cwd(),"content","articles");for(const e of(await readdir(ar,{withFileTypes:true})).filter(x=>x.isDirectory()))try{let a=JSON.parse(await readFile(path.join(ar,e.name,"article.json"),"utf8")),z=a?.media?.sourceImageUrl;if(typeof z=="string"&&/^https?:\/\//i.test(z))jobs.push({slug:a.slug||e.name,url:z,page:a?.media?.sourcePageUrl||a?.sources?.[0]||null})}catch{}
const src=await map(jobs,5,async j=>{let r=await fetch(j.url,{headers:{"user-agent":"BusinessFutureToday/0.6 (+https://businessfuture.today)",accept:"image/avif,image/webp,image/png,image/jpeg,image/gif,*/*"},redirect:"follow",signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`SOURCE ${r.status} ${j.slug}`);let t=(r.headers.get("content-type")||"").split(";")[0].toLowerCase();if(!t.startsWith("image/"))throw Error(`NOT_IMAGE ${j.slug}`);let b=Buffer.from(await r.arrayBuffer());if(!b.length||b.length>20000000)throw Error(`SIZE ${j.slug}`);let ext=t=="image/jpeg"?"jpg":t=="image/png"?"png":t=="image/webp"?"webp":t=="image/avif"?"avif":t=="image/gif"?"gif":"img",k=`source-images/${j.slug}/hero/original.${ext}`;await put(S,k,b,t);await put(S,`source-images/${j.slug}/hero/manifest.json`,Buffer.from(JSON.stringify({slug:j.slug,sourcePageUrl:j.page,sourceImageUrl:j.url,contentType:t,bytes:b.length,archivedAt:new Date().toISOString()},null,2)),"application/json");return{ok:true}});
let pf=pub.filter(x=>!x?.ok).length,sf=src.filter(x=>!x?.ok).length;console.log(JSON.stringify({public:{attempted:files.length,uploaded:pub.length-pf,failed:pf},source:{attempted:jobs.length,uploaded:src.length-sf,failed:sf}},null,2));
