import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {PublicationFooter,PublicationHeader,StoryLink} from "@/components/publication/chrome";
import {liveStories} from "@/lib/live-content";
import {canonicalTemplate} from "@/lib/publication";
import {publicationSections,sectionBySlug,sectionHref,storiesInSection} from "@/lib/sections";

const PAGE_SIZE=18;
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{category:string}>}):Promise<Metadata>{const{category:slug}=await params;const section=sectionBySlug(slug);if(!section)return{};return{title:section.name,description:section.description,alternates:{canonical:`https://businessfuture.today${sectionHref(section)}`}}}
export default async function CategoryPage({params,searchParams}:{params:Promise<{category:string}>;searchParams:Promise<{page?:string}>}){const[{category:slug},query]=await Promise.all([params,searchParams]);const section=sectionBySlug(slug);if(!section)notFound();const all=storiesInSection(await liveStories(),section.name);const pages=Math.max(1,Math.ceil(all.length/PAGE_SIZE));const page=Math.min(pages,Math.max(1,Number.parseInt(query.page||"1",10)||1));const items=all.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);return <main className="publication publication--newsroom"><PublicationHeader template={canonicalTemplate}/><section className="pub-category-page__hero pub-shell"><p className="pub-kicker">SECTION</p><div><h1>{section.name}</h1><p>{section.description}</p></div><span>{all.length} stories</span></section><section className="pub-shell pub-category-page__grid">{items.map(story=><article key={story.slug} className="pub-category-page__card"><StoryLink slug={story.slug} template={canonicalTemplate} className="pub-category-page__media">{story.cardImage||story.heroImage?<img src={story.cardImage||story.heroImage||""} alt={story.imageAlt||story.title}/>:<div className="pub-image pub-image--fallback"><span>BFT</span></div>}</StoryLink><p className="pub-kicker">{story.kicker}</p><h2><StoryLink slug={story.slug} template={canonicalTemplate}>{story.title}</StoryLink></h2><p>{story.dek}</p><div className="pub-meta"><span>{story.author?`${story.author.name} · ${story.author.desk}`:section.name}</span><span>{story.readTime}</span></div></article>)}</section>{pages>1?<nav className="pub-pagination pub-shell" aria-label="Section pages">{page>1?<Link href={`${sectionHref(section)}?page=${page-1}`}>← Newer</Link>:<span/>}<span>Page {page} of {pages}</span>{page<pages?<Link href={`${sectionHref(section)}?page=${page+1}`}>Older →</Link>:<span/>}</nav>:null}<PublicationFooter template={canonicalTemplate}/></main>}
